# Generated by Django 2.2.5 on 2019-09-24 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagonostic_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='user_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
