# Generated by Django 2.2.5 on 2019-09-24 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagonostic_management', '0002_doctor_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='user_name',
            new_name='username',
        ),
    ]
